### ISSUE TITLE
MPRIS example exposes incorrect validation

### ISSUE THREAD

**Issue by ioangogo** [acrisci/node-dbus-next#27]
I was messing about with the MPRIS example on my KDE based desktop and discovered that KDE's browser intergration was casusing issues with this libary as its bus name is `org.mpris.MediaPlayer2.plasma-browser-integration` and is causing this error 
```
Error: Invalid interface name: org.mpris.MediaPlayer2.plasma-browser-integration
    at assertInterfaceNameValid (/home/iloosley/node_modules/dbus-next/lib/validators.js:108:11)
    at new ProxyObject (/home/iloosley/node_modules/dbus-next/lib/client/proxy-object.js:35:5)
    at MessageBus.getProxyObject (/home/iloosley/node_modules/dbus-next/lib/bus.js:162:15)
    at main (/home/iloosley/mpris.js:111:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
![image](https://user-images.githubusercontent.com/7449028/58640345-c4618c80-82f0-11e9-95fb-a1866c1fec8c.png)

This appears to be because the library is incorrectly validating the bus name as an interface. MPRIS player addresses are[ bus names](https://specifications.freedesktop.org/mpris-spec/latest/#Bus-Name-Policy), interfaces are things like 
```
org.mpris.MediaPlayer2.Player
org.mpris.MediaPlayer2.TrackList
org.mpris.MediaPlayer2.Playlists
```

**Comment by acrisci** [comment]
:+1:
